### ISSUE TITLE
CoD2 1.3?

### ISSUE THREAD

**Issue by kungfooman** [ineedbots/cod2m#1]
The description of the repo says:

`A server/client modification for Call of Duty 2 (latest Windows).`

However, I don't really know what that means. Latest Windows = Windows 11... or do you mean latest patch = 1.3?

So in short, is this all about CoD2 1.3?

**Comment by ineedbots** [comment]
1.3 Windows, ill edit it to make it more clear

**Comment by kungfooman** [comment]
Thanks a lot!
